package ai.x.grok.api.completions;

/*
 * Copyright (C) 2026 Key Bridge. All rights reserved. Use is subject to license
 * terms.
 *
 * This software code is protected by Copyrights and remains the property of
 * Key Bridge. Key Bridge reserves all rights in and to
 * Copyrights and no license is granted under Copyrights in this Software
 * License Agreement.
 *
 * Key Bridge may license Copyrights for commercialization pursuant to
 * the terms of either a Standard Software Source Code License Agreement or a
 * Standard Product License Agreement. A copy of either Agreement can be
 * obtained upon request by sending an email to info@keybridgewireless.com.
 *
 * All information contained herein is the property of Key Bridge.
 * The intellectual and technical concepts contained herein
 * are proprietary.
 */
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

/**
 * The chat request body for {@code /v1/chat/completions} endpoint.
 * <p>
 * First pass: text completions only. {@link Message} content is a string, with
 * system, user, and assistant roles. The following schema properties are
 * stubbed out of this tree and are not included: {@code tools},
 * {@code tool_choice}, {@code parallel_tool_calls}, {@code search_parameters},
 * {@code web_search_options}.
 *
 * @author Key Bridge
 * @since v1.1.0 created 2026-09-08
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ChatRequest {

  /**
   * If set to {@code true}, the request returns a {@code request_id}. You can
   * then get the deferred response by GET
   * {@code /v1/chat/deferred-completion/{request_id}}.
   */
  @JsonProperty("deferred")
  private Boolean deferred;

  /**
   * (Not supported by reasoning models) Number between -2.0 and 2.0. Positive
   * values penalize new tokens based on their existing frequency in the text so
   * far, decreasing the model's likelihood to repeat the same line verbatim.
   */
  @JsonProperty("frequency_penalty")
  private Float frequencyPenalty;

  /**
   * (Unsupported) A JSON object that maps tokens (specified by their token ID
   * in the tokenizer) to an associated bias value from -100 to 100.
   * Mathematically, the bias is added to the logits generated by the model
   * prior to sampling. The exact effect will vary per model, but values between
   * -1 and 1 should decrease or increase likelihood of selection; values like
   * -100 or 100 should result in a ban or exclusive selection of the relevant
   * token.
   */
  @JsonProperty("logit_bias")
  private Map<Integer, Float> logitBias;

  /**
   * Whether to return log probabilities of the output tokens or not. If true,
   * returns the log probabilities of each output token returned in the content
   * of message.
   */
  @JsonProperty("logprobs")
  private Boolean logprobs;

  /**
   * An upper bound for the number of tokens that can be generated for a
   * completion, only applies to visible output tokens (i.e. does not apply to
   * tokens used for reasoning or function calls). Defaults to None, meaning the
   * model will generate as many tokens as needed up until the model's maximum
   * context length.
   */
  @JsonProperty("max_completion_tokens")
  private Integer maxCompletionTokens;

  /**
   * The maximum number of tokens that can be generated in the chat completion.
   * Deprecated in favor of {@code max_completion_tokens}.
   *
   * @deprecated use {@link #maxCompletionTokens}
   */
  @Deprecated
  @JsonProperty("max_tokens")
  private Integer maxTokens;

  /**
   * A list of messages that make up the the chat conversation. Different models
   * support different message types, such as image and text.
   */
  @JsonProperty("messages")
  private List<Message> messages;

  /**
   * Model name for the model to use. Obtainable from
   * https://console.x.ai/team/default/models or
   * https://docs.x.ai/docs/models.
   */
  @JsonProperty("model")
  private String model;

  /**
   * How many chat completion choices to generate for each input message. Note
   * that you will be charged based on the number of generated tokens across all
   * of the choices. Keep n as 1 to minimize costs.
   */
  @JsonProperty("n")
  private Integer n;

  /**
   * (Not supported by {@code grok-3} and reasoning models) Number between -2.0
   * and 2.0. Positive values penalize new tokens based on whether they appear
   * in the text so far, increasing the model's likelihood to talk about new
   * topics.
   */
  @JsonProperty("presence_penalty")
  private Float presencePenalty;

  /**
   * Constrains how hard a reasoning model thinks before responding. Not
   * supported by {@code grok-4} and will result in error if used with
   * {@code grok-4}. Possible values are {@code low} (uses fewer reasoning
   * tokens) and {@code high} (uses more reasoning tokens).
   */
  @JsonProperty("reasoning_effort")
  private String reasoningEffort;

  /**
   * An object specifying the format that the model must output. Specify
   * {@code {"type": "json_object"}} for JSON output, or
   * {@code {"type": "json_schema", "json_schema": {...}}} for structured
   * outputs. If {@code {"type": "text"}}, the model will return a text
   * response.
   */
  @JsonProperty("response_format")
  private ResponseFormat responseFormat;

  /**
   * If specified, our system will make a best effort to sample
   * deterministically, such that repeated requests with the same {@code seed}
   * and parameters should return the same result. Determinism is not
   * guaranteed, and you should refer to the {@code system_fingerprint} response
   * parameter to monitor changes in the backend.
   */
  @JsonProperty("seed")
  private Integer seed;

  /**
   * (Not supported by reasoning models) Up to 4 sequences where the API will
   * stop generating further tokens.
   */
  @JsonProperty("stop")
  private List<String> stop;

  /**
   * If set, partial message deltas will be sent. Tokens will be sent as
   * data-only server-sent events as they become available, with the stream
   * terminated by a {@code data: [DONE]} message.
   */
  @JsonProperty("stream")
  private Boolean stream;

  /**
   * Options for streaming response. Only set this when you set
   * {@code stream: true}.
   */
  @JsonProperty("stream_options")
  private StreamOptions streamOptions;

  /**
   * What sampling temperature to use, between 0 and 2. Higher values like 0.8
   * will make the output more random, while lower values like 0.2 will make it
   * more focused and deterministic.
   */
  @JsonProperty("temperature")
  private Float temperature;

  /**
   * An integer between 0 and 8 specifying the number of most likely tokens to
   * return at each token position, each with an associated log probability.
   * logprobs must be set to true if this parameter is used.
   */
  @JsonProperty("top_logprobs")
  private Integer topLogprobs;

  /**
   * An alternative to sampling with {@code temperature}, called nucleus
   * sampling, where the model considers the results of the tokens with
   * {@code top_p} probability mass. So 0.1 means only the tokens comprising the
   * top 10% probability mass are considered. It is generally recommended to
   * alter this or {@code temperature} but not both.
   */
  @JsonProperty("top_p")
  private Float topP;

  /**
   * A unique identifier representing your end-user, which can help xAI to
   * monitor and detect abuse.
   */
  @JsonProperty("user")
  private String user;

  //<editor-fold defaultstate="collapsed" desc="Accessors">
  public Boolean getDeferred() {
    return deferred;
  }

  public void setDeferred(Boolean deferred) {
    this.deferred = deferred;
  }

  public Float getFrequencyPenalty() {
    return frequencyPenalty;
  }

  public void setFrequencyPenalty(Float frequencyPenalty) {
    this.frequencyPenalty = frequencyPenalty;
  }

  public Map<Integer, Float> getLogitBias() {
    return logitBias;
  }

  public void setLogitBias(Map<Integer, Float> logitBias) {
    this.logitBias = logitBias;
  }

  public Boolean getLogprobs() {
    return logprobs;
  }

  public void setLogprobs(Boolean logprobs) {
    this.logprobs = logprobs;
  }

  public Integer getMaxCompletionTokens() {
    return maxCompletionTokens;
  }

  public void setMaxCompletionTokens(Integer maxCompletionTokens) {
    this.maxCompletionTokens = maxCompletionTokens;
  }

  /**
   * @deprecated use {@link #getMaxCompletionTokens()}
   */
  @Deprecated
  public Integer getMaxTokens() {
    return maxTokens;
  }

  /**
   * @deprecated use {@link #setMaxCompletionTokens(Integer)}
   */
  @Deprecated
  public void setMaxTokens(Integer maxTokens) {
    this.maxTokens = maxTokens;
  }

  public List<Message> getMessages() {
    return messages;
  }

  public void setMessages(List<Message> messages) {
    this.messages = messages;
  }

  public String getModel() {
    return model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public Integer getN() {
    return n;
  }

  public void setN(Integer n) {
    this.n = n;
  }

  public Float getPresencePenalty() {
    return presencePenalty;
  }

  public void setPresencePenalty(Float presencePenalty) {
    this.presencePenalty = presencePenalty;
  }

  public String getReasoningEffort() {
    return reasoningEffort;
  }

  public void setReasoningEffort(String reasoningEffort) {
    this.reasoningEffort = reasoningEffort;
  }

  public ResponseFormat getResponseFormat() {
    return responseFormat;
  }

  public void setResponseFormat(ResponseFormat responseFormat) {
    this.responseFormat = responseFormat;
  }

  public Integer getSeed() {
    return seed;
  }

  public void setSeed(Integer seed) {
    this.seed = seed;
  }

  public List<String> getStop() {
    return stop;
  }

  public void setStop(List<String> stop) {
    this.stop = stop;
  }

  public Boolean getStream() {
    return stream;
  }

  public void setStream(Boolean stream) {
    this.stream = stream;
  }

  public StreamOptions getStreamOptions() {
    return streamOptions;
  }

  public void setStreamOptions(StreamOptions streamOptions) {
    this.streamOptions = streamOptions;
  }

  public Float getTemperature() {
    return temperature;
  }

  public void setTemperature(Float temperature) {
    this.temperature = temperature;
  }

  public Integer getTopLogprobs() {
    return topLogprobs;
  }

  public void setTopLogprobs(Integer topLogprobs) {
    this.topLogprobs = topLogprobs;
  }

  public Float getTopP() {
    return topP;
  }

  public void setTopP(Float topP) {
    this.topP = topP;
  }

  public String getUser() {
    return user;
  }

  public void setUser(String user) {
    this.user = user;
  }
  //</editor-fold>
}
