package com.xai.api.responses.usage;

import com.fasterxml.jackson.annotation.JsonProperty;

public class OutputTokensDetails {

  /**
   * Tokens generated by the model for reasoning.
   */
  @JsonProperty("reasoning_tokens")
  private int reasoningTokens;

  public int getReasoningTokens() {
    return reasoningTokens;
  }

  public void setReasoningTokens(int reasoningTokens) {
    this.reasoningTokens = reasoningTokens;
  }
}
