package com.xai.api.responses.input.part.item;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;

@JsonTypeName("function_call_output")
public class FunctionToolCallOutput implements ModelInputItemPayload {

  /**
   * The type of the function tool call, which is always `function_call_output`.
   */
  @JsonProperty("type")
  private String // always "function_call_output"
    type = "function_call_output";

  /**
   * The unique ID of the function tool call generated by the model.
   */
  @JsonProperty("call_id")
  private String callId;

  /**
   * The output of the function tool call, as a JSON string.
   */
  @JsonProperty("output")
  private String output;

  public FunctionToolCallOutput() {
  }

  public FunctionToolCallOutput(String callId, String output) {
    this.callId = callId;
    this.output = output;
  }

  /**
   * Returns The unique ID of the function tool call generated by the model.
   *
   * @return the call_id
   */
  public String getCallId() {
    return callId;
  }

  /**
   * Sets The unique ID of the function tool call generated by the model.
   *
   * @param callId the call_id
   */
  public void setCallId(String callId) {
    this.callId = callId;
  }

  /**
   * Returns The output of the function tool call, as a JSON string.
   *
   * @return the output
   */
  public String getOutput() {
    return output;
  }

  /**
   * Sets The output of the function tool call, as a JSON string.
   *
   * @param output the output
   */
  public void setOutput(String output) {
    this.output = output;
  }

  /**
   * Returns The type of the function tool call, which is always
   * `function_call_output`.
   *
   * @return the type
   */
  public String getType() {
    return type;
  }

  /**
   * Sets The type of the function tool call, which is always
   * `function_call_output`.
   *
   * @param type the type
   */
  public void setType(String type) {
    this.type = type;
  }

}
