package com.xai.api.responses.output.tool;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.xai.api.responses.output.ModelOutput;
import com.xai.api.type.OutputType;

@JsonTypeName("custom_tool_call")
public class CustomToolCall extends ModelOutput {

  /**
   * An identifier used to map this custom tool call to a tool call output.
   */
  private String name;
  /**
   * The unique ID of the function tool call generated by the model.
   */
  @JsonProperty("call_id")
  private String callId;

  /**
   * The unique ID of the custom tool call,
   */
  private String input;

  public CustomToolCall() {
    super(OutputType.custom_tool_call);
  }

  public String getCallId() {
    return callId;
  }

  public void setCallId(String callId) {
    this.callId = callId;
  }

  /**
   * Returns The unique ID of the custom tool call,
   *
   * @return the input
   */
  public String getInput() {
    return input;
  }

  /**
   * Sets The unique ID of the custom tool call,
   *
   * @param input the input
   */
  public void setInput(String input) {
    this.input = input;
  }

  /**
   * Returns An identifier used to map this custom tool call to a tool call
   * output.
   *
   * @return the name
   */
  public String getName() {
    return name;
  }

  /**
   * Sets An identifier used to map this custom tool call to a tool call output.
   *
   * @param name the name
   */
  public void setName(String name) {
    this.name = name;
  }
}
