package com.xai.api.responses.output.tool;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.xai.api.responses.output.ModelOutput;
import com.xai.api.type.OutputType;

/**
 * These two types form the backbone of: Tool-using agents in the Responses API
 * <p>
 * FunctionToolCall
 * <p>
 * FunctionToolCallOutput
 * <p>
 * Everything else is orchestration.
 *
 * @author Key Bridge
 */
@JsonTypeName("function_call")
public class FunctionToolCall extends ModelOutput {

  /**
   * The name of the function.
   */
  private String name;

  /**
   * The unique ID of the function tool call generated by the model.
   */
  @JsonProperty("call_id")
  private String callId;

  /**
   * The arguments to pass to the function, as a JSON string.
   */
  private String arguments;

  // Status: completed, in_progress, incomplete
  // The type of the tool call:
  // "function_call", "web_search_call", "x_search_call",
  // "code_interpreter_call", or "mcp_call"
  public FunctionToolCall() {
    super(OutputType.function_call);
  }

  /**
   * Returns The arguments to pass to the function, as a JSON string.
   *
   * @return the arguments
   */
  public String getArguments() {
    return arguments;
  }

  /**
   * Sets The arguments to pass to the function, as a JSON string.
   *
   * @param arguments the arguments
   */
  public void setArguments(String arguments) {
    this.arguments = arguments;
  }

  public String getCallId() {
    return callId;
  }

  public void setCallId(String callId) {
    this.callId = callId;
  }

  /**
   * Returns The name of the function.
   *
   * @return the name
   */
  public String getName() {
    return name;
  }

  /**
   * Sets The name of the function.
   *
   * @param name the name
   */
  public void setName(String name) {
    this.name = name;
  }
}
