package com.xai.api.images.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

public class GeneratedImage {

  /**
   * A base64-encoded string representation of the generated image in `jpeg`
   * encoding, if `b64_json` is specified as `response_format` in the request.
   */
  @JsonProperty("b64_json")
  private String b64Json;

  /**
   * The revised prompt generated by a chat model from the original prompt. This
   * prompt is used in the final image generation.
   */
  @JsonProperty("revised_prompt")
  private String revisedPrompt;

  /**
   * A url to the generated image, if `response_format` is not specified or with
   * `url` in the request.
   */
  @JsonProperty("url")
  private String url;

  public String getB64Json() {
    return b64Json;
  }

  public void setB64Json(String b64Json) {
    this.b64Json = b64Json;
  }

  public String getRevisedPrompt() {
    return revisedPrompt;
  }

  public void setRevisedPrompt(String revisedPrompt) {
    this.revisedPrompt = revisedPrompt;
  }

  /**
   * Returns A url to the generated image, if `response_format` is not specified
   * or with `url` in the request.
   *
   * @return the url
   */
  public String getUrl() {
    return url;
  }

  /**
   * Sets A url to the generated image, if `response_format` is not specified or
   * with `url` in the request.
   *
   * @param url the url
   */
  public void setUrl(String url) {
    this.url = url;
  }
}
