package com.xai.api.video.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

public class GeneratedVideo {

  /**
   * Duration of the generated video in seconds.
   */
  @JsonProperty("duration")
  private int duration;

  /**
   * Whether the video generated by the model respects moderation rules. The
   * field will be true if the video respects moderation rules. Otherwise the
   * field will be false and the video url field will be empty.
   */
  @JsonProperty("respect_moderation")
  private boolean respectModeration;

  /**
   * A url to the generated video.
   */
  @JsonProperty("url")
  private String url;

  /**
   * Returns Duration of the generated video in seconds.
   *
   * @return the duration
   */
  public int getDuration() {
    return duration;
  }

  /**
   * Sets Duration of the generated video in seconds.
   *
   * @param duration the duration
   */
  public void setDuration(int duration) {
    this.duration = duration;
  }

  /**
   * Returns A url to the generated video.
   *
   * @return the url
   */
  public String getUrl() {
    return url;
  }

  /**
   * Sets A url to the generated video.
   *
   * @param url the url
   */
  public void setUrl(String url) {
    this.url = url;
  }

  public boolean isRespectModeration() {
    return respectModeration;
  }

  public void setRespectModeration(boolean respectModeration) {
    this.respectModeration = respectModeration;
  }
}
