package com.xai.api.batch.completion;



import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Represents a generated chat completion message.
 */
public class ChoiceMessage {

  /**
   * The role that the message belongs to (always "assistant").
   */
  @JsonProperty("role")
  private String role;

  /**
   * The content of the message.
   */
  @JsonProperty("content")
  private String content;

  /**
   * The reasoning trace generated by the model.
   */
  @JsonProperty("reasoning_content")
  private String reasoningContent;

  /**
   * The refusal reason if the model cannot generate a response.
   */
  @JsonProperty("refusal")
  private String refusal;

  /**
   * A list of tool calls requested by the model.
   */
  @JsonProperty("tool_calls")
  private List<ToolCall> toolCalls;

  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public String getReasoningContent() {
    return reasoningContent;
  }

  public void setReasoningContent(String reasoningContent) {
    this.reasoningContent = reasoningContent;
  }

  public String getRefusal() {
    return refusal;
  }

  public void setRefusal(String refusal) {
    this.refusal = refusal;
  }

  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public List<ToolCall> getToolCalls() {
    return toolCalls;
  }

  public void setToolCalls(List<ToolCall> toolCalls) {
    this.toolCalls = toolCalls;
  }
}
