package com.xai.api.batch.completion;



import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Details of completion usage.
 */
public class CompletionUsageDetail {

  /**
   * Tokens generated by the model for reasoning.
   */
  @JsonProperty("reasoning_tokens")
  private int reasoningTokens;

  /**
   * Audio input tokens generated by the model.
   */
  @JsonProperty("audio_tokens")
  private int audioTokens;

  /**
   * Tokens in the prediction that appeared in the completion.
   */
  @JsonProperty("accepted_prediction_tokens")
  private int acceptedPredictionTokens;

  /**
   * Tokens in the prediction that did not appear in the completion.
   */
  @JsonProperty("rejected_prediction_tokens")
  private int rejectedPredictionTokens;

  public int getAcceptedPredictionTokens() {
    return acceptedPredictionTokens;
  }

  public void setAcceptedPredictionTokens(int acceptedPredictionTokens) {
    this.acceptedPredictionTokens = acceptedPredictionTokens;
  }

  public int getAudioTokens() {
    return audioTokens;
  }

  public void setAudioTokens(int audioTokens) {
    this.audioTokens = audioTokens;
  }

  public int getReasoningTokens() {
    return reasoningTokens;
  }

  public void setReasoningTokens(int reasoningTokens) {
    this.reasoningTokens = reasoningTokens;
  }

  public int getRejectedPredictionTokens() {
    return rejectedPredictionTokens;
  }

  public void setRejectedPredictionTokens(int rejectedPredictionTokens) {
    this.rejectedPredictionTokens = rejectedPredictionTokens;
  }
}
