package com.xai.api.responses;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.xai.api.responses.output.ModelOutput;
import com.xai.api.responses.tool.ModelTool;
import com.xai.api.responses.tool.ModelToolChoice;
import com.xai.api.responses.usage.ModelUsage;
import com.xai.api.type.ResponseStatus;
import java.time.Clock;
import java.time.Instant;
import java.util.List;

/**
 * required "created_at" "id" "model" "object" "output" "parallel_tool_calls"
 * "text" "tool_choice" "tools" "status" "store" "metadata" "background"
 * "service_tier" "truncation" "top_logprobs" "presence_penalty"
 * "frequency_penalty"
 * <pre>
 *  ModelResponse
 * ├── IncompleteDetails          (via incomplete_details)
 * ├── ReasoningConfiguration     (via reasoning)
 * ├── ModelOutput                (via output – array of)
 * │   └── (nested content types referenced inside ModelOutput items)
 * │       ├── output_text        (via content type)
 * │       └── (other possible content types, not named as top-level schemas)
 * └── ModelUsage                 (via usage)
 *     ├── PromptUsageDetail      (via prompt_tokens_details)
 *     └── CompletionUsageDetail  (via completion_tokens_details)
 * </pre>
 *
 * @author Key Bridge
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class ModelResponse {

  /**
   * Unique ID of the response.
   */
  private String id;
  /**
   * The object type of this resource. Always set to `response`.
   */
  private String object = "response";
  /**
   * Model name used to generate the response.
   */
  private String model;
  /**
   * The UTC Unix timestamp (in seconds) for the response creation time.
   */
  @JsonProperty("created_at")
  private long createdAt;
  /**
   * The UTC Unix timestamp (in seconds) for the response completion time. Only
   * set when the response is completed.
   */
  @JsonProperty("completed_at")
  private Long completedAt;
  /**
   * Status of the response. One of `completed`, `in_progress` or `incomplete`.
   */
  private ResponseStatus status;
  /**
   * The response generated by the model.
   * <p>
   * Typically, in the ModelResponse from xAI's /v1/responses endpoint, the
   * output list (List<ModelOutput> output) contains 1 to 4 items in the vast
   * majority of real-world calls.
   * <p>
   * Most common patterns (90–95% of calls) Single item – plain text reply
   * <p>
   * This is by far the most frequent case when:
   * <p>
   * no tools are enabled, <br>
   * no reasoning mode is active, <br>
   * no safety refusal occurs, <br>
   * simple chat / instruction-style prompt.
   * <p>
   * You can safely optimize most of your code around this pattern.
   * <p>
   * Two items – reasoning + final text
   * <p>
   * → Very common when using reasoning-capable models (grok-4 variants with
   * reasoning enabled) or when the prompt asks for step-by-step thinking.
   * <p>
   * Less common but still frequent (5–10%) Tool call(s) + final message
   * <p>
   * → Appears when tools are enabled and the model decides to use one or more
   * (especially parallel tool calls).
   * <p>
   * Multiple messages (rare, but happens)
   * <p>
   * → Seen in longer agentic flows, when the model produces incremental
   * answers, corrections, or multi-paragraph structured replies.
   * <p>
   * Rare / edge cases (less than 1%)
   * <p>
   * Refusal + fallback text → Only when a safety filter partially triggers.
   */
  private List<ModelOutput> output;
  /**
   * Token usage information.
   */
  private ModelUsage usage;
  /**
   * Reasoning configuration. Only for reasoning models.
   */
  private Object reasoning;
  /**
   * "#/components/schemas/ModelToolChoice"
   * <p>
   * Either an enumerated statement or the directed tool.
   * <p>
   * Use either: getToolChoiceMode or getToolChoiceFunction
   * <p>
   * Controls which (if any) tool is called by the model. auto means the model
   * can pick between generating a message or calling one or more tools.
   * required means the model must call one or more tools. Specifying a
   * particular tool via `{"type": "function", "function": {"name":
   * "my_function"}}` forces the model to call that tool. `none` is the default
   * when no tools are present. `auto` is the default if tools are present.
   */
  @JsonProperty("tool_choice")
  private ModelToolChoice toolChoice;
  /**
   * A list of tools the model may call in JSON-schema. Currently, only
   * functions and web search are supported as tools. A max of 128 tools are
   * supported.
   */
  private List<ModelTool> tools;
  /**
   * Whether to allow the model to run parallel tool calls.
   */
  @JsonProperty("parallel_tool_calls")
  private Boolean parallelToolCalls;
  /**
   * What sampling temperature to use, between 0 and 2. Higher values like 0.8
   * will make the output more random, while lower values like 0.2 will make it
   * more focused and deterministic.
   */
  private Float temperature;
  /**
   * An alternative to sampling with `temperature`, called nucleus sampling,
   * where the model considers the results of the tokens with `top_p`
   * probability mass. So 0.1 means only the tokens comprising the top 10%
   * probability mass are considered. It is generally recommended to alter this
   * or `temperature` but not both.
   */
  @JsonProperty("top_p")
  private Float topP;
  /**
   * Whether to store the input message(s) and model response for later
   * retrieval.
   */
  private boolean store;
  /**
   * The ID of the previous response from the model.
   */
  @JsonProperty("previous_response_id")
  private String previousResponseId;
  /**
   * Details about why the response is incomplete.
   */
  @JsonProperty("incomplete_details")
  private Object incompleteDetails;  //--------------------------------------------------------------------------
  // 3. Deprecated / not-supported / compatibility-only / rarely/never useful
  //--------------------------------------------------------------------------
  // Whether to process asynchronously (OpenResponses compatibility)
  //  private Boolean background;
  // Error object (if any)
  //  private Object error;
  // (Not supported) Frequency penalty
  //  @JsonProperty("frequency_penalty")  private Float frequencyPenalty; // (NOT SUPPORTED in Responses API)
  // (Not supported) Presence penalty
  //  @JsonProperty("presence_penalty")  private Float presencePenalty; // (NOT SUPPORTED in Responses API)
  // System/developer instructions injected into context
  //  private String instructions;
  // Max output tokens (output + reasoning)
  //  @JsonProperty("max_output_tokens")  private Integer maxOutputTokens;
  // Maximum number of tool calls allowed
  //  @JsonProperty("max_tool_calls")  private Integer maxToolCalls;
  // Compatibility metadata
  //  private Map<String, Object> metadata;	// "Only included for compatibility."
  // Cache key for routing
  //  @JsonProperty("prompt_cache_key")  private String promptCacheKey;
  // Stable identifier for safety monitoring
  //  @JsonProperty("safety_identifier")  private String safetyIdentifier;
  /**
   * Specifies the processing tier used for serving the request.
   */
  @JsonProperty("service_tier")
  private String serviceTier;  // Text response configuration
  //  private ModelResponseConfiguration text;
  // Number of top logprobs returned
  /**
   * An integer between 0 and 8 specifying the number of most likely tokens to
   * return at each token position.
   */
  @JsonProperty("top_logprobs")
  private Integer topLogprobs;
  /**
   * Truncation strategy
   * <p>
   * It is usually not returned in the response body unless you explicitly set
   * it in the request (in which case it is echoed back as-is). When present, it
   * is always one of those three strings.
   */
  //  private TruncationStrategy truncation;
  /**
   * A unique identifier representing your end-user, which can help xAI to
   * monitor and detect abuse.
   */
  private String user;

  //<editor-fold defaultstate="collapsed" desc="Getter and Setter">
  public Long getCompletedAt() {
    return completedAt;
  }

  public void setCompletedAt(Long completedAt) {
    this.completedAt = completedAt;
  }

  public long getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(long createdAt) {
    this.createdAt = createdAt;
  }

  /**
   * Returns Unique ID of the response.
   *
   * @return the id
   */
  public String getId() {
    return id;
  }

  /**
   * Sets Unique ID of the response.
   *
   * @param id the id
   */
  public void setId(String id) {
    this.id = id;
  }

  public Object getIncompleteDetails() {
    return incompleteDetails;
  }

  public void setIncompleteDetails(Object incompleteDetails) {
    this.incompleteDetails = incompleteDetails;
  }

  /**
   * Returns Model name used to generate the response.
   *
   * @return the model
   */
  public String getModel() {
    return model;
  }

  /**
   * Sets Model name used to generate the response.
   *
   * @param model the model
   */
  public void setModel(String model) {
    this.model = model;
  }

  /**
   * Returns The object type of this resource. Always set to `response`.
   *
   * @return the object
   */
  public String getObject() {
    return object;
  }

  /**
   * Sets The object type of this resource. Always set to `response`.
   *
   * @param object the object
   */
  public void setObject(String object) {
    this.object = object;
  }

  /**
   * Returns The response generated by the model.
   *
   * @return the output
   */
  public List<ModelOutput> getOutput() {
    return output;
  }

  /**
   * Sets The response generated by the model.
   *
   * @param output the output
   */
  public void setOutput(List<ModelOutput> output) {
    this.output = output;
  }

  public Boolean getParallelToolCalls() {
    return parallelToolCalls;
  }

  /**
   * Null-safe helper method to test the internal {@link #parallelToolCalls}
   * field value.
   *
   * @return whether the requested tools may be called in parallel (true) or
   *         must be called sequentially (false)
   */
  @JsonIgnore
  public boolean isParallelToolCalls() {
    if (parallelToolCalls != null) {
      return parallelToolCalls.booleanValue();
    } else {
      return false;
    }
  }

  public void setParallelToolCalls(Boolean parallelToolCalls) {
    this.parallelToolCalls = parallelToolCalls;
  }

  public String getPreviousResponseId() {
    return previousResponseId;
  }

  public void setPreviousResponseId(String previousResponseId) {
    this.previousResponseId = previousResponseId;
  }

  /**
   * Returns Reasoning configuration. Only for reasoning models.
   *
   * @return the reasoning
   */
  public Object getReasoning() {
    return reasoning;
  }

  /**
   * Sets Reasoning configuration. Only for reasoning models.
   *
   * @param reasoning the reasoning
   */
  public void setReasoning(Object reasoning) {
    this.reasoning = reasoning;
  }

  public String getServiceTier() {
    return serviceTier;
  }

  public void setServiceTier(String serviceTier) {
    this.serviceTier = serviceTier;
  }

  /**
   * Returns Status of the response. One of `completed`, `in_progress` or
   * `incomplete`.
   *
   * @return the status
   */
  public ResponseStatus getStatus() {
    return status;
  }

  /**
   * Sets Status of the response. One of `completed`, `in_progress` or
   * `incomplete`.
   *
   * @param status the status
   */
  public void setStatus(ResponseStatus status) {
    this.status = status;
  }

  /**
   * Returns Whether to store the input message(s) and model response for later
   * retrieval.
   *
   * @return the store
   */
  public boolean getStore() {
    return store;
  }

  /**
   * Sets Whether to store the input message(s) and model response for later
   * retrieval.
   *
   * @param store the store
   */
  public void setStore(boolean store) {
    this.store = store;
  }

  /**
   * Returns What sampling temperature to use, between 0 and 2. Higher values
   * like 0.8 will make the output more random, while lower values like 0.2 will
   * make it more focused and deterministic.
   *
   * @return the temperature
   */
  public Float getTemperature() {
    return temperature;
  }

  /**
   * Sets What sampling temperature to use, between 0 and 2. Higher values like
   * 0.8 will make the output more random, while lower values like 0.2 will make
   * it more focused and deterministic.
   *
   * @param temperature the temperature
   */
  public void setTemperature(Float temperature) {
    this.temperature = temperature;
  }

  public ModelToolChoice getToolChoice() {
    return toolChoice;
  }

  public void setToolChoice(ModelToolChoice toolChoice) {
    this.toolChoice = toolChoice;
  }

  /**
   * Returns A list of tools the model may call in JSON-schema. Currently, only
   * functions and web search are supported as tools. A max of 128 tools are
   * supported.
   *
   * @return the tools
   */
  public List<ModelTool> getTools() {
    return tools;
  }

  /**
   * Sets A list of tools the model may call in JSON-schema. Currently, only
   * functions and web search are supported as tools. A max of 128 tools are
   * supported.
   *
   * @param tools the tools
   */
  public void setTools(List<ModelTool> tools) {
    this.tools = tools;
  }

  public Integer getTopLogprobs() {
    return topLogprobs;
  }

  public void setTopLogprobs(Integer topLogprobs) {
    this.topLogprobs = topLogprobs;
  }

  public Float getTopP() {
    return topP;
  }

  public void setTopP(Float topP) {
    this.topP = topP;
  }

  /**
   * Returns Token usage information.
   *
   * @return the usage
   */
  public ModelUsage getUsage() {
    return usage;
  }

  /**
   * Sets Token usage information.
   *
   * @param usage the usage
   */
  public void setUsage(ModelUsage usage) {
    this.usage = usage;
  }

  /**
   * Returns A unique identifier representing your end-user, which can help xAI
   * to monitor and detect abuse.
   *
   * @return the user
   */
  public String getUser() {
    return user;
  }

  /**
   * Sets A unique identifier representing your end-user, which can help xAI to
   * monitor and detect abuse.
   *
   * @param user the user
   */
  public void setUser(String user) {
    this.user = user;
  }
  //</editor-fold>

  // Extensions
  /**
   * Key Bridge extension recording the timestamp when this object was created.
   *
   * @return the timestamp
   */
  @JsonIgnore
  public Instant getCreated() {
    return Instant.ofEpochSecond(createdAt);
  }

  /**
   * The UTC Unix timestamp for the response completion time. Returns the
   * current timestamp if the response failed to complete successfully (always
   * non-null).
   */
  @JsonIgnore
  public Instant getCompleted() {
    return completedAt == null ? Instant.now(Clock.systemUTC()) : Instant.ofEpochSecond(completedAt);
  }

  @Override
  public String toString() {
    return "ModelResponse{" + "id=" + id + ", object=" + object + ", model=" + model + ", createdAt=" + createdAt + ", completedAt=" + completedAt + ", status=" + status + ", output=" + output + ", usage=" + usage + ", reasoning=" + reasoning + ", toolChoice=" + toolChoice + ", tools=" + tools + ", parallelToolCalls=" + parallelToolCalls + ", temperature=" + temperature + ", topP=" + topP + ", store=" + store + ", previousResponseId=" + previousResponseId + ", incompleteDetails=" + incompleteDetails + '}';
  }
}
